[package]
name = "rust-crash-course"
version = "0.1.0"
authors = ["factorlive <24828335+factorlive@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
